### ISSUE TITLE
Sandy and snowy shrines.

### ISSUE THREAD

**Issue by huntergames084** [viliger2/ShrineOfRepair#1]
I think (but not sure) that hopoo made different variants of the shrines by making them completely different objects, like they made a version that only spawns in snowy maps, and another version that only spawns in sandy maps.

**Comment by viliger2** [comment]
From what I gathered while digging through game models and debug console, each shrine (that has variants that is) has "Showy" and "Sandy" models.  
The problem for me is that I don't know, yet, how to filter where interactable spawns. In early development I've had an issue, where upon entering Planetarium the map was filled with my new shrine and nothing else, but thankfully that was an issue with R2API and I didn't have to fix it. 
I will probably dig through other mods, like Clayman, for example. They only spawn on specific stages so it shouldn't be that much of an issue.

**Comment by huntergames084** [comment]
Good to know.
